# Generated by Django 5.0.1 on 2024-01-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_order_orderitem_order_items_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
